# Generated by Django 4.2 on 2024-11-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Builiding",
            fields=[
                (
                    "building_num",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="건물번호"
                    ),
                ),
                (
                    "building_name",
                    models.CharField(max_length=30, unique=True, verbose_name="건물명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "facility_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="편의시설 아이디",
                    ),
                ),
                (
                    "facility_category",
                    models.CharField(max_length=10, verbose_name="편의시설 카테고리"),
                ),
                ("facility_name", models.CharField(max_length=20, verbose_name="시설명")),
                ("facility_loc", models.CharField(max_length=5, verbose_name="층수")),
                (
                    "facility_desc",
                    models.CharField(max_length=30, verbose_name="시설 설명"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_set",
                        to="facilities.builiding",
                        verbose_name="건물번호",
                    ),
                ),
            ],
        ),
    ]
