# Generated by Django 4.2 on 2024-11-09 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestStuNumber",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profile_name", models.CharField(max_length=20, unique=True)),
                (
                    "profile_student_number",
                    models.PositiveIntegerField(verbose_name="학번"),
                ),
                ("profile_gubun", models.CharField(max_length=20)),
                ("profile_agreement", models.BooleanField(default=False)),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("profile_grade", models.FloatField(default=0)),
                ("grad_research", models.BooleanField(default=False)),
                ("grad_exam", models.BooleanField(default=False)),
                ("grad_pro", models.BooleanField(default=False)),
                ("grad_certificate", models.BooleanField(default=False)),
                ("for_language", models.BooleanField(default=False)),
                (
                    "for_language_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="외국어 시험명"
                    ),
                ),
                (
                    "for_language_score",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="외국어 시험점수"
                    ),
                ),
            ],
        ),
    ]
