# Generated by Django 4.2 on 2024-11-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0002_alter_exceptiongenedsubject_unique_together"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="double_or_minor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="double_minor",
                to="requirements.department",
                verbose_name="이중/부전공 학과",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="double_or_minor_college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="double_minor_college",
                to="requirements.college",
                verbose_name="이중/부전공 대학",
            ),
        ),
    ]
