# Generated by Django 4.2 on 2024-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(max_length=20),
        ),
    ]
