# Generated by Django 4.2 on 2024-11-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_gubun",
            field=models.CharField(
                max_length=20, verbose_name="이중전공, 부전공, 전공심화, 전공심화+부전공"
            ),
        ),
    ]
