# Generated by Django 4.2 on 2024-11-20 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_double_or_minor_and_more"),
        ("accounts", "0003_alter_profile_profile_name"),
    ]

    operations = []
