# Generated by Django 4.2 on 2024-11-20 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0002_alter_exceptiongenedsubject_unique_together"),
        ("accounts", "0004_merge_20241120_0125"),
    ]

    operations = [
        migrations.AddField(
            model_name="requeststunumber",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="requirements.college",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
