# Generated by Django 4.2 on 2024-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_requeststunumber_college_alter_profile_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="double_for_language",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_for_language_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="외국어 시험명"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_for_language_score",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="외국어 시험점수"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_grad_certificate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_grad_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_grad_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="double_grad_research",
            field=models.BooleanField(default=False),
        ),
    ]
