# Generated by Django 5.0.7 on 2024-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_profile_double_for_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="grad_required_completed",
            field=models.BooleanField(default=False),
        ),
    ]
