# Generated by Django 5.0.7 on 2024-11-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_profile_grad_required_completed"),
        ("requirements", "0006_alter_subjectgenedrequired_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="major",
                to="requirements.department",
                verbose_name="학과",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="major_college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="major_college",
                to="requirements.college",
                verbose_name="대학",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_gubun",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="이중전공, 부전공, 전공심화, 전공심화+부전공",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_student_number",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="학번"),
        ),
    ]
