# Generated by Django 4.2 on 2024-11-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("requirements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organ",
            fields=[
                (
                    "organ_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="기관 아이디"
                    ),
                ),
                ("organ_name", models.CharField(max_length=50, verbose_name="기관명")),
                ("organ_link", models.URLField(verbose_name="기관 페이지 url")),
            ],
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscribe_major",
                    models.BooleanField(default=False, verbose_name="본전공 구독 여부"),
                ),
                (
                    "subscribe_double",
                    models.BooleanField(default=False, verbose_name="이중전공 구독 여부"),
                ),
                (
                    "subscribe_ai",
                    models.BooleanField(default=False, verbose_name="ai 교육원 구독 여부"),
                ),
                (
                    "subscribe_foreign",
                    models.BooleanField(default=False, verbose_name="국제교류원 교육원 구독 여부"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "notice_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="알림 고유번호"
                    ),
                ),
                ("notice_link", models.URLField(verbose_name="알림 url")),
                (
                    "notice_read",
                    models.BooleanField(default=False, verbose_name="알림 읽음 여부"),
                ),
                (
                    "notice_title",
                    models.CharField(max_length=200, verbose_name="알림 제목"),
                ),
                ("notice_date", models.DateField(verbose_name="알림 날짜")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.department",
                    ),
                ),
                (
                    "notice_organ",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notices.organ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
