# Generated by Django 4.2 on 2024-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="subscribe_cfl",
            field=models.BooleanField(default=False, verbose_name="진로취업지원센터"),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="subscribe_flex",
            field=models.BooleanField(default=False, verbose_name="FLEX 센터"),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="subscribe_foreign_edu",
            field=models.BooleanField(default=False, verbose_name="외국어교육센터"),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="subscribe_special_foreign",
            field=models.BooleanField(default=False, verbose_name="특수외국어교육진흥원"),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="subscribe_ai",
            field=models.BooleanField(default=False, verbose_name="AI 교육원 구독 여부"),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="subscribe_foreign",
            field=models.BooleanField(default=False, verbose_name="국제교류팀 교육원 구독 여부"),
        ),
    ]
