# Generated by Django 4.2 on 2024-11-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectdepartment",
            name="subject_department_date",
        ),
        migrations.RemoveField(
            model_name="subjectdepartment",
            name="subject_department_room",
        ),
        migrations.RemoveField(
            model_name="subjectgened",
            name="subject_gened_date",
        ),
        migrations.RemoveField(
            model_name="subjectgened",
            name="subject_gened_room",
        ),
        migrations.AddField(
            model_name="requirement",
            name="description",
            field=models.CharField(
                max_length=100, null=True, verbose_name="기타사항(예를 들면 시험 대체가능)"
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="graduation_gubun",
            field=models.CharField(
                max_length=20, null=True, verbose_name="이중전공,부전공,전공심화"
            ),
        ),
        migrations.AddField(
            model_name="subjectdepartment",
            name="subject_department_room_date",
            field=models.CharField(max_length=50, null=True, verbose_name="강의시간/강의실"),
        ),
        migrations.AddField(
            model_name="subjectgened",
            name="subject_gened_room_date",
            field=models.CharField(max_length=50, null=True, verbose_name="강의시간/강의실"),
        ),
        migrations.AlterField(
            model_name="college",
            name="college_required_credit",
            field=models.IntegerField(null=True, verbose_name="졸업이수학점"),
        ),
        migrations.AlterField(
            model_name="foreigntestrequired",
            name="test_basic_score",
            field=models.CharField(
                max_length=20, null=True, verbose_name="요건 통과 기준 점수"
            ),
        ),
        migrations.AlterField(
            model_name="requiredcredit",
            name="required_credit_sn",
            field=models.CharField(max_length=50, verbose_name="학번(이상)"),
        ),
        migrations.AlterField(
            model_name="subjectdepartmentrequired",
            name="subject_gened_required_sn",
            field=models.CharField(max_length=30, verbose_name="학번(이상)"),
        ),
        migrations.AlterField(
            model_name="subjectgenedrequired",
            name="subject_gened_required_sn",
            field=models.CharField(max_length=30, verbose_name="학번(이상)"),
        ),
        migrations.CreateModel(
            name="ExtraForeignTest",
            fields=[
                (
                    "extra_test_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="기타시험 아이디"
                    ),
                ),
                (
                    "extra_test_name",
                    models.CharField(max_length=30, verbose_name="기타시험 이름"),
                ),
                (
                    "extra_test_basic_score",
                    models.CharField(max_length=20, null=True, verbose_name="기준"),
                ),
                (
                    "extra_test_gubun",
                    models.CharField(max_length=20, verbose_name="졸시/자격증"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="추가정보/예를 들면 이중만 조건 다른 경우",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.department",
                    ),
                ),
            ],
        ),
    ]
