# Generated by Django 4.2 on 2024-11-14 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exceptiongenedsubject",
            unique_together={
                ("subject_gened_required_code", "comparison_code", "department")
            },
        ),
    ]
