# Generated by Django 4.2 on 2024-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "requirements",
            "0002_remove_subjectdepartment_subject_department_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="description",
            field=models.CharField(
                max_length=500, null=True, verbose_name="기타사항(예를 들면 시험 대체가능)"
            ),
        ),
    ]
