# Generated by Django 4.2 on 2024-11-13 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0003_alter_requirement_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectdepartmentrequired",
            old_name="subject_gened_required_sn",
            new_name="subject_department_required_sn",
        ),
        migrations.AlterUniqueTogether(
            name="subjectdepartmentrequired",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subjectgenedrequired",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subjectdepartmentrequired",
            name="subject_department_required_code",
            field=models.CharField(max_length=50, null=True, verbose_name="전공 필수 과목코드"),
        ),
        migrations.AddField(
            model_name="subjectdepartmentrequired",
            name="subject_department_required_db",
            field=models.BooleanField(default=False, verbose_name="본전공만 해당 여부"),
        ),
        migrations.AddField(
            model_name="subjectdepartmentrequired",
            name="subject_department_required_desc",
            field=models.CharField(max_length=500, null=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="subjectdepartmentrequired",
            name="subject_department_required_instead",
            field=models.BooleanField(default=False, verbose_name="대체 가능 여부"),
        ),
        migrations.AddField(
            model_name="subjectdepartmentrequired",
            name="subject_department_required_name",
            field=models.CharField(max_length=20, null=True, verbose_name="전공필수 과목명"),
        ),
        migrations.AddField(
            model_name="subjectgenedrequired",
            name="subject_gened_required_code",
            field=models.CharField(max_length=50, null=True, verbose_name="교양 필수 과목코드"),
        ),
        migrations.AddField(
            model_name="subjectgenedrequired",
            name="subject_gened_required_desc",
            field=models.CharField(max_length=500, null=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="subjectgenedrequired",
            name="subject_gened_required_instead",
            field=models.BooleanField(default=False, verbose_name="대체 가능 여부"),
        ),
        migrations.AddField(
            model_name="subjectgenedrequired",
            name="subject_gened_required_name",
            field=models.CharField(max_length=20, null=True, verbose_name="교양필수 과목명"),
        ),
        migrations.AlterUniqueTogether(
            name="subjectdepartmentrequired",
            unique_together={("subject_department_required_code", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectgenedrequired",
            unique_together={("subject_gened_required_code", "department")},
        ),
        migrations.RemoveField(
            model_name="subjectdepartmentrequired",
            name="subject_gened_required_db",
        ),
        migrations.RemoveField(
            model_name="subjectdepartmentrequired",
            name="subject_requirement",
        ),
        migrations.RemoveField(
            model_name="subjectgenedrequired",
            name="subject_gened",
        ),
        migrations.CreateModel(
            name="ExceptionGenedSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_code",
                    models.CharField(max_length=50, verbose_name="대체 과목코드"),
                ),
                (
                    "comparison_name",
                    models.CharField(max_length=20, verbose_name="대체 과목명"),
                ),
                (
                    "code_match",
                    models.BooleanField(default=False, verbose_name="코드값 일치"),
                ),
                (
                    "name_match",
                    models.BooleanField(default=False, verbose_name="과목명 일치"),
                ),
                (
                    "subject_gened_required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.subjectgenedrequired",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject_gened_required", "comparison_code")},
            },
        ),
        migrations.CreateModel(
            name="ExceptionDepartmentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_code",
                    models.CharField(max_length=50, verbose_name="대체 과목코드"),
                ),
                (
                    "comparison_name",
                    models.CharField(max_length=20, verbose_name="대체 과목명"),
                ),
                (
                    "code_match",
                    models.BooleanField(default=False, verbose_name="코드값 일치"),
                ),
                (
                    "name_match",
                    models.BooleanField(default=False, verbose_name="과목명 일치"),
                ),
                (
                    "subject_department_required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.subjectdepartmentrequired",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject_department_required", "comparison_code")},
            },
        ),
    ]
