# Generated by Django 4.2 on 2024-11-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0005_alter_generalsubjectcompleted_completed_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectgenedrequired", unique_together=set(),
        ),
    ]
